---
- name: Install Docker Repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: 'https://download.docker.com/linux/centos/7/$basearch/stable'
    enabled: true
    gpgcheck: true
    gpgkey: 'https://download.docker.com/linux/centos/gpg'

- name: Install Docker-CE
  yum:
    name:
      - docker-ce
      - python-pip
    state: present

- name: Install docker-compose python
  pip:
    name:
      - docker-compose
      - docker

- name: Enable Docker
  systemd:
    name: docker
    state: started
    enabled: true

- name: Create Compose File
  template:
    src: docker-compose.yml
    dest: /opt/docker-compose.yml

- name: Create Cert
  copy:
    src: star.tbevan.us.crt
    dest: /opt/tbevan.us.crt

- name: Create Key
  copy:
    src: star.tbevan.us.key
    dest: /opt/tbevan.us.key

- name: Compose UP
  docker_compose:
    project_src: /opt

- name: Configure firewall
  firewalld:
    zone: public
    state: enabled
    service: "{{item}}"
    permanent: yes
    immediate: yes
  with_items:
    - http
    - https
