---
- name: Install RPM packages
  yum:
    name:
      - docker-ce
      - python3-pip
      - make
      - git
      - gcc
      - binutils
      - python3
      - python3-devel
      - python-devel
    state: present

- name: Upgrade PIP
  pip:
    state: latest
    name:
      - pip

- name: Install PIP packages
  pip:
    state: latest
    name:
      - docker-compose
      - docker
      - more_itertools

- name: Upgrade PIP
  pip:
    executable: pip3
    state: latest
    name:
      - pip

- name: Install PIP packages
  pip:
    executable: pip3
    state: latest
    name:
      - docker
      - pelican

- name: Enable Docker
  systemd:
    name: docker
    state: started
    enabled: true

- name: Create Compose File
  template:
    src: docker-compose.yml
    dest: /opt/docker-compose.yml

- name: Create Cert
  copy:
    src: star.tbevan.us.crt
    dest: /opt/tbevan.us.crt

- name: Create Key
  copy:
    src: star.tbevan.us.key
    dest: /opt/tbevan.us.key

- name: Git clone repo
  git:
    repo: https://github.com/tylerbevan/recipes.tbevan.us.git
    dest: /opt/recipes

- name: Build html contents
  make:
    chdir: /opt/recipes
    target: html

- name: Compose UP
  docker_compose:
    project_src: /opt

- name: Configure firewall
  firewalld:
    zone: public
    state: enabled
    service: "{{item}}"
    permanent: yes
    immediate: yes
  with_items:
    - http
    - https
