---
- name: Update all packages to latest
  dnf:
    name: "*"
    state: latest

- name: Install common packages
  dnf:
    name:
      - vim-enhanced
      - bsdtar
      - zip
      - unzip
      - p7zip
      - tmux
      - wget
      - rsync
      - pexpect

- name: Check if kernel version changed
  shell: needs-restarting -r
  changed_when: false
  failed_when: false
  register: kernel_check

- name: Reboot due to kernel update
  reboot:
  when: ((kernel_check.stdout_lines | length) > 0) and (kernel_check.rc == 1)