---
- name: Create Terraform backend config
  delegate_to: localhost
  template:
    src: config.tf.j2
    dest: "{{ playbook_dir }}/terraform-envs/envs/{{ tf_env }}/config.tf"
- name: Call Terraform
  delegate_to: localhost
  terraform:
    project_path: "{{ playbook_dir }}/terraform-envs/envs/{{ tf_env }}"
    state: present
    force_init: true
  register: tf_output

- set_fact:
    ansible_host: "{{ tf_output['outputs']['ip_addr']['value'] }}"

- name: Wait for VM to be up
  wait_for_connection:

- raw: yum install -y python3

- setup:
